<font size=3;>
<p style="text-align: right;"> Lab Solution --- <b>NOT FOR DISTRIBUTION!</b> </p>
</font>

# Lab C1: Weighted Average

## Setup

In [2]:
# Import some useful functions
from numpy import *
from numpy.random import *
from datascience import *
from statsmodels.formula.api import *

# Define some useful functions
def correlation(array_1, array_2):
    return corrcoef(array_1, array_2).item(1)

# Customize look of graphics
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
plt.rcParams['figure.dpi'] = 60
%matplotlib inline

# Force display of all values 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Hide some unnecessary warning messages
import warnings
warnings.filterwarnings("ignore")
import numpy
numpy.int = numpy.int_

## Airline Reservations

### Business Decision

The Manager of Travel Operations is considering setting a policy to encourage his company's executives to do business travel on either of two specific airlines.  He needs to account for how the airlines are suited to the kind of business travel typical of the executives and the airlines' prices.

# BEGIN QUESTION
name: q1
manual: false
points: 
    - 1
    - 1

### Data

The dataset comprises a random sample of recent roundtrip tickets purchased from 2 airlines for travel between New York’s John F. Kennedy Airport (JFK) and Los Angeles Airport (LAX). Each ticket is described by the following variables:

* `carrier`: the airline
* `rtrip_fare`: round trip fare
* `advance`: number of days in advance of the flight that ticket was purchased
* `busclass`: indicator for business class ('1' if business class, '0' if not)
* `nonrefundable`: indicator for whether a ticket was nonrefundable ('1' if nonrefundable, '0' if refundable)
* `satstayover`: indicator for whether a roundtrip ticket includes a Saturday stayover in the destination location

Retrieve the airline ticket dataset, show the number of observations and the first few observations.

# BEGIN SOLUTION

In [4]:
data = Table.read_table('ticket_prices.csv') # SOLUTION
data.num_rows # SOLUTION
data

10266

carrier | rtrip_fare | advance | busclass | nonrefundable | satstayover
AA      | 158        | 14      | 0        | 1             | 0
AA      | 159        | 52      | 0        | 1             | 1
AA      | 159        | 15      | 0        | 1             | 0
AA      | 160        | 28      | 0        | 1             | 1
AA      | 160        | 24      | 0        | 1             | 1
AA      | 160        | 28      | 0        | 1             | 0
AA      | 165        | 22      | 0        | 1             | 1
AA      | 165        | 15      | 0        | 1             | 0
AA      | 165        | 17      | 0        | 1             | 1
AA      | 165        | 26      | 0        | 1             | 1
... (10256 rows omitted)

# END SOLUTION

# BEGIN TESTS

In [5]:
data.num_rows == 10266

True

In [6]:
data.labels == ('carrier', 'rtrip_fare', 'advance', 'busclass', 'nonrefundable', 'satstayover')

True

# END TESTS

# END QUESTION

# BEGIN QUESTION
name: q2_1
manual: false
points: 
    - 1
    - 1

### Analysis | Weighted Averages of Groups

Calculate the mean and median prices.

# BEGIN SOLUTION

In [7]:
mean_price = mean(data.column('rtrip_fare')) # SOLUTION
median_price = median(data.column('rtrip_fare')) # SOLUTION

# END SOLUTION

# BEGIN TESTS

In [7]:
round(mean_price) == 369

True

In [8]:
round(median_price) == 328

True

# END TESTS

# END QUESTION

# BEGIN QUESTION
name: q2_2
manual: false
points: 
    - 1

For each airline, calculate the number of flights.

# BEGIN SOLUTION

In [15]:
airline_flights = data.group('carrier') # SOLUTION
airline_flights

carrier | count
AA      | 7021
UA      | 3245

# END SOLUTION

# BEGIN TESTS

In [16]:
all(airline_flights.labels == array(['carrier', 'count']))

True

In [17]:
all(airline_flights.column('carrier') == ['AA', 'UA'])

True

# END TESTS

# END QUESTION

# BEGIN QUESTION
name: q2_3
manual: false
points: 
    - 1
    - 1

Calculate statistics to show whether one airline is much cheaper than the other, on average.

# BEGIN SOLUTION

In [18]:
airline_mean_prices = data.group('carrier', mean) # SOLUTION
airline_mean_prices

carrier | rtrip_fare mean | advance mean | busclass mean | nonrefundable mean | satstayover mean
AA      | 368.894         | 17.3988      | 0.0276314     | 0.977923           | 0.207663
UA      | 368.579         | 16.9174      | 0.00246533    | 0.999384           | 0.247458

# END SOLUTION

# BEGIN TESTS

In [19]:
all(airline_mean_prices.labels == array(['carrier', 'rtrip_fare mean', 'advance mean', 'busclass mean', 'nonrefundable mean', 'satstayover mean']))

True

In [21]:
all(airline_mean_prices.column('carrier') == ['AA', 'UA'])

True

# END TESTS

# END QUESTION

# BEGIN QUESTION
name: q2_4
manual: false
points: 
    - 1
    - 1

Calculate statistics to show whether flights with Saturday stayovers are much cheaper than other flights, on average.

# BEGIN SOLUTION

In [25]:
d = data.group('satstayover', mean)
d

diff_satstayover = d.column('rtrip_fare mean').item(0) - d.column('rtrip_fare mean').item(1)
diff_satstayover

satstayover | carrier mean | rtrip_fare mean | advance mean | busclass mean | nonrefundable mean
0           |              | 401.882         | 14.2394      | 0.0234853     | 0.981262
1           |              | 251.649         | 27.8939      | 0.00619195    | 0.996904

150.2329283914493

# END SOLUTION

# BEGIN TESTS

In [24]:
all(d.column('satstayover') == [0, 1])

True

In [26]:
round(diff_satstayover) == 150

True

# END TESTS

# END QUESTION

<p style="text-align:left; font-size:10px;">
Copyright (c) Huntsinger Associates, LLC
<span style="float:right;">
Document revised September 1, 2023
</span>
</p>